<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords" tests="8" time="13.154" ignored="0" failures="0" timestamp="11 Apr 2018 11:46:57 GMT" skipped="5" hostname="RIPLBRD50" errors="2">
  <testcase name="verifiyLoginWithDifferentRecords" time="3.118" classname="com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords"/>
  <testcase name="verifiyLoginWithDifferentRecords" time="0.002" classname="com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords">
    <skipped/>
  </testcase> <!-- verifiyLoginWithDifferentRecords -->
  <testcase name="verifiyLoginWithDifferentRecords" time="0.002" classname="com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords">
    <skipped/>
  </testcase> <!-- verifiyLoginWithDifferentRecords -->
  <testcase name="verifiyLoginWithDifferentRecords" time="10.004" classname="com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords.verifiyLoginWithDifferentRecords() didn&#039;t finish within the time-out 10000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords.verifiyLoginWithDifferentRecords() didn't finish within the time-out 10000
	at java.lang.Throwable.printStackTrace(Throwable.java:643)
	at java.lang.Throwable.printStackTrace(Throwable.java:634)
	at com.test.automation.UIAutomation.LoginPage.LoginPage.loginToApplication(LoginPage.java:68)
	at com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords.verifiyLoginWithDifferentRecords(VerifiyLoginWithDifferentRecords.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifiyLoginWithDifferentRecords -->
  <testcase name="close" time="0.000" classname="com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords">
    <error type="org.openqa.selenium.SessionNotCreatedException" message="Tried to run command without establishing a connection
Build info: version: &#039;3.5.3&#039;, revision: &#039;a88d25fe6b&#039;, time: &#039;2017-08-29T12:42:44.417Z&#039;
System info: host: &#039;RIPLBRD50&#039;, ip: &#039;192.168.1.72&#039;, os.name: &#039;Windows 7&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;6.1&#039;, java.version: &#039;1.8.0_111&#039;
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{moz:profile=C:\Users\YOGESH~1\AppData\Local\Temp\rust_mozprofile.mLtd0cb01xIu, rotatable=false, timeouts={implicit=0, pageLoad=300000, script=30000}, pageLoadStrategy=normal, platform=XP, specificationLevel=0, moz:accessibilityChecks=false, webdriver.remote.sessionid=2bb79600-33cb-4ecd-ad58-0604d1a43e8f, acceptInsecureCerts=false, browserVersion=55.0, platformVersion=6.1, moz:processID=9172, browserName=firefox, javascriptEnabled=true, platformName=XP}]
Session ID: 2bb79600-33cb-4ecd-ad58-0604d1a43e8f">
      <![CDATA[org.openqa.selenium.SessionNotCreatedException: Tried to run command without establishing a connection
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:42:44.417Z'
System info: host: 'RIPLBRD50', ip: '192.168.1.72', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_111'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{moz:profile=C:\Users\YOGESH~1\AppData\Local\Temp\rust_mozprofile.mLtd0cb01xIu, rotatable=false, timeouts={implicit=0, pageLoad=300000, script=30000}, pageLoadStrategy=normal, platform=XP, specificationLevel=0, moz:accessibilityChecks=false, webdriver.remote.sessionid=2bb79600-33cb-4ecd-ad58-0604d1a43e8f, acceptInsecureCerts=false, browserVersion=55.0, platformVersion=6.1, moz:processID=9172, browserName=firefox, javascriptEnabled=true, platformName=XP}]
Session ID: 2bb79600-33cb-4ecd-ad58-0604d1a43e8f
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:185)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:120)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:646)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:703)
	at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:542)
	at com.test.automation.UIAutomation.testBase.TestBase.close(TestBase.java:450)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:357)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1289)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </error>
  </testcase> <!-- close -->
  <testcase name="verifiyLoginWithDifferentRecords" time="0.002" classname="com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords">
    <skipped/>
  </testcase> <!-- verifiyLoginWithDifferentRecords -->
  <testcase name="verifiyLoginWithDifferentRecords" time="0.025" classname="com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords">
    <skipped/>
  </testcase> <!-- verifiyLoginWithDifferentRecords -->
  <testcase name="verifiyLoginWithDifferentRecords" time="0.001" classname="com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords">
    <skipped/>
  </testcase> <!-- verifiyLoginWithDifferentRecords -->
</testsuite> <!-- com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords -->
